In [ ]:
#unzipping the directory of generated images
!unzip cifar10_1.zip

#cloning a repo which has state of the art classifier for CIFAR10
!git clone https://github.com/SHI-Labs/Compact-Transformers.git

In [ ]:
%cd Compact-Transformers


/content/Compact-Transformers


In [ ]:
from src import cct_7_3x1_32
model = cct_7_3x1_32(pretrained=True, progress=True)



Downloading: "https://shi-labs.com/projects/cct/checkpoints/pretrained/cct_7_3x1_32_cifar10_300epochs.pth" to /root/.cache/torch/hub/checkpoints/cct_7_3x1_32_cifar10_300epochs.pth


  0%|          | 0.00/14.4M [00:00<?, ?B/s]

In [ ]:
import torch
import torch.nn as nn
import torch.optim
import torch.utils.data
import torchvision.transforms as transforms
import torchvision
import torch.utils.data as data 

In [ ]:
#loading data from the cifar10 generated images folder for classification
test_data = torchvision.datasets.ImageFolder(root="/content/cifar10", transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.4914, 0.4822, 0.4465],
                         std=[0.2470, 0.2435, 0.2616])
    ]))

test_data_loader  = data.DataLoader(test_data, batch_size=256, shuffle=True)


In [ ]:
#classification logic

import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score


if torch.cuda.is_available():      
    device = torch.device("cuda")

else:
    device = torch.device("cpu")

print(device)

model.eval()
model.to(device)
loss_val, acc1_val = 0, 0
n = 0
correct = 0
x = torch.empty(0).to(device)
y = torch.empty(0).to(device)


with torch.no_grad():
    for i, (images, targets) in enumerate(test_data_loader):
        images = images.to(device)
        targets = targets.to(device)
        output = model(images)
        output = torch.argmax(output,1)
        
        x = torch.cat((x,output),0)
        y = torch.cat((y,targets),0)
        
        n += images.size(0)
        if n % 500 == 0:
          print(n)
        

y = np.round(y.cpu().detach().numpy(),0)
x = np.round(x.cpu().detach().numpy(),0)





cuda
10000


In [ ]:
#printing the metrics
print("Avg accuracy = ", accuracy_score(y, x))
print("Confusion matrix = ", confusion_matrix(y, x))
print("Precesion Total = ", precision_score(y, x , average='micro'))
print("Precision classwise = ", precision_score(y, x , average=None))
print("Recall Total = ", recall_score(y, x , average='micro'))
print("Recall classwise = ", recall_score(y, x , average=None))
print("F1 Total = ", f1_score(y, x , average='micro'))
print("F1 classwise = ", f1_score(y, x , average=None))


Avg accuracy =  0.9993
Confusion matrix =  [[ 998    0    2    0    0    0    0    0    0    0]
 [   0 1000    0    0    0    0    0    0    0    0]
 [   0    0 1000    0    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0    0 1000    0    0    0    0    0]
 [   0    0    0    2    0  998    0    0    0    0]
 [   0    0    0    0    0    0 1000    0    0    0]
 [   0    0    0    0    1    0    0  999    0    0]
 [   2    0    0    0    0    0    0    0  998    0]
 [   0    0    0    0    0    0    0    0    0 1000]]
Precesion Total =  0.9993
Precision classwise =  [0.998      1.         0.99800399 0.99800399 0.999001   1.
 1.         1.         1.         1.        ]
Recall Total =  0.9993
Recall classwise =  [0.998 1.    1.    1.    1.    0.998 1.    0.999 0.998 1.   ]
F1 Total =  0.9993
F1 classwise =  [0.998      1.         0.999001   0.999001   0.99950025 0.998999
 1.         0.99949975 0.998999   1.        ]
